dist: xenial
language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r tests/requirements.txt"
  - "pip install codecov"

# split the test run according to
# http://blog.travis-ci.com/2012-11-28-speeding-up-your-tests-by-parallelizing-them/
env:
  global:
    - PYTHONHASHSEED=random  # test for ordered dict use
  matrix:
    - TESTS=tests/

# command to run tests
script: "python -b -m pytest -v --cov=privacyidea $TESTS"

after_success: 
    - codecov
