language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r tests/requirements.txt"
  - "pip install codecov"

# split the test run according to
# http://blog.travis-ci.com/2012-11-28-speeding-up-your-tests-by-parallelizing-them/
env:
  global:
    - PYTHONHASHSEED=random  # test for ordered dict use
  matrix:
    - TESTS=tests/

matrix:
    allow_failures:
       - python: 3.5

# command to run tests
script: "python -b -m pytest -v --cov=privacyidea $TESTS"

after_success: 
    - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aeb7493dbe5c478e6c2b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
