language: python
python:
  - 2.7
  - 2.6
  - 3.4
# command to install dependencies
install:
  - "pip install ."
  - "pip install mock"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
# split the test run according to
# http://blog.travis-ci.com/2012-11-28-speeding-up-your-tests-by-parallelizing-them/
#env:
#  - TESTSCRIPT=tests/test_api_system.py
#  - TESTSCRIPT=tests/test_api_token.py
#  - TESTSCRIPT=tests/test_api_users.py
#  - TESTSCRIPT=tests/test_api_validate.py
#  - TESTSCRIPT=tests/test_db_model.py
#  - TESTSCRIPT=tests/test_lib_apps.py
#  - TESTSCRIPT=tests/test_lib_config.py
#  - TESTSCRIPT=tests/test_lib_crypto.py
#  - TESTSCRIPT=tests/test_lib_importotp.py
#  - TESTSCRIPT=tests/test_lib_policy.py
#  - TESTSCRIPT=tests/test_lib_realm.py
#  - TESTSCRIPT=tests/test_lib_resolver.py
#  - TESTSCRIPT=tests/test_lib_tokenclass.py
#  - TESTSCRIPT=tests/test_lib_token.py
#  - TESTSCRIPT=tests/test_lib_tokens_hotp.py
#  - TESTSCRIPT=tests/test_lib_tokens_passwordtoken.py
#  - TESTSCRIPT=tests/test_lib_tokens_totp.py
#  - TESTSCRIPT=tests/test_lib_tokens_yubikey.py
#  - TESTSCRIPT=tests/test_lib_user.py
#  - TESTSCRIPT=tests/test_resolver_realm.py
matrix:
    allow_failures:
       - python: 2.6
       - python: 3.4
# command to run tests
#script: "nosetests -v --with-coverage --cover-package=privacyidea $TESTSCRIPT"
script: "nosetests -v --with-coverage --cover-package=privacyidea"

after_success: 
    coveralls --rcfile=coveragerc
