dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# check if we need to run travis
before_install: ./.travis_check.sh; ret=$?; if [ $ret -eq 123 ]; then travis_terminate 0; elif [
  $ret -ne 0 ]; then travis_terminate $ret; fi

# command to install dependencies
install:
  - "pip install -r tests/requirements.txt"
  - "pip install ."
  - "pip install codecov"

# split the test run according to
# http://blog.travis-ci.com/2012-11-28-speeding-up-your-tests-by-parallelizing-them/
env:
  global:
    - PYTHONHASHSEED=random  # test for ordered dict use
  matrix:
    - TESTS=tests/

# command to run tests
script: "python -b -m pytest -v --cov=privacyidea $TESTS"

after_success: 
    - codecov
