version: 2.1

executors:
  mysql:
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: mysql+pymysql://pi:test123@localhost/pi
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: pi
          MYSQL_USER: pi
          MYSQL_PASSWORD: test123
          MYSQL_RANDOM_ROOT_PASSWORD: yes
  postgres: &postgres-executor
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql+psycopg2://pi:test123@localhost/pi
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_DB: pi
          POSTGRES_USER: pi
          POSTGRES_PASSWORD: test123

jobs:
  test_generic:
    description: Run all tests with the latest packages
    docker:
      # in the long run we could use matrix tests here for multiple python versions
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: mkdir -p test-results/generic
      - run: pip install -U pip
      # We do not want any caching (always the latest packages) therefore we
      # install the packages directly (not using the python orb)
      - run: pip install pytest pytest-cov mock responses testfixtures
      - run: pip install -e .
      - run: pip freeze > test-results/generic/packages.txt
      - run:
          command: |
            python -b -m pytest --cov=privacyidea --junit-xml=test-results/generic/results.xml tests/
          name: Test generic
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/generic

  test_database:
    parameters:
      db:
        type: string
    description: Run all tests with << parameters.db >> database backend
    executor: << parameters.db >>
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: v1-deps-{{ checksum "requirements.txt" }}
      - run: pip install -U pip
      - run: pip install -r tests/requirements.txt
      - when:
          condition:
            # see https://circleci.com/docs/configuration-reference#logic-statements
            equal: [*postgres-executor, << parameters.db >> ]
          steps:
            - run: pip install psycopg2
      - run: mkdir -p test-results/<< parameters.db >>
      - run:
          command: |
            python -b -m pytest --cov=privacyidea --junit-xml=test-results/<< parameters.db >>/results.xml tests/
          name: << parameters.db >> Test
      - save_cache:
          paths:
            - "${PYENV_ROOT}"
          key: v1-deps-{{ checksum "requirements.txt" }}
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/<< parameters.db >>

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          # Start the nightly test at 5:00 UTC only on branch "master"
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_generic
      - test_database:
          matrix:
            parameters:
              db: ['mysql', 'postgres']
