# SPDX-FileCopyrightText: (C) 2014 NetKnights GmbH <https://netknights.it>
# SPDX-License-Identifier: CC0-1.0
#
name: Run WebUI tests
on:
  # run on each push to every branch of the repository but only on
  # pull requests to the 'master' and 'branch-*' branches
  push:
    paths:
      # Only run when there are changes in the new WebUI directory
      - 'privacyidea/static_new/**'
  pull_request:
    branches:
      - 'master'
      - 'branch-*'
    paths:
      - 'privacyidea/static_new/**'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./privacyidea/static_new

jobs:
  test-webui:
    name: Run tests for WebUI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Node.js for testing the new WebUI
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: lts/*  # Use the latest LTS-release
          cache: npm
          cache-dependency-path: privacyidea/static_new/package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build the new WebUI
        run: npm run test
